### ISSUE TITLE
npm install error 

### ISSUE THREAD

**Issue by NTUwilliam** [googlecartographer/point_cloud_viewer#166]
Hi ! 
I'm trying to install point_cloud_viewer to visualize the map generated by the 3D Cartographer. 

When I'm installing the **### Web Viewer** in step 4, I met a **npm install error** shown as follows:
![npm error](https://user-images.githubusercontent.com/43923666/47148574-a1efa580-d303-11e8-9b3f-21eb12a688e3.png)

Then there's no `octree_web_viewer` generated so cannot see the visualized map.
I think it's a error similar with the closed issue [https://github.com/googlecartographer/cartographer_ros/issues/271](url). 
Do you have any suggestions? Any comment is appreciated. Thanks a lot !
@SirVer @thomasschiwietz

**Comment by SirVer** [comment]
There is no error in your screenshot. If you run `cargo build --release`, then cd ~/point_cloud_viewer-master` and run `target/release/octree_web_viewer <your octree>` you should be golden.

**Comment by SirVer** [comment]
The warn is inconsequential. The binary you want is `points_web_viewer`, sorry for giving the wrong name above.

**Comment by NTUwilliam** [comment]
@SirVer Thx a lot! It's working.

BTW, why don't you change the `../target/release/octree_web_viewer <octree directory>` in the repository of the [https://github.com/googlecartographer/point_cloud_viewer](url) into the correct `../target/release/points_web_viewer <octree directory>` to avoid misleading others? :)

**Comment by SirVer** [comment]
@NTUwilliam As you will have guessed, this error is not there to mislead, but because it is an error. I am currently swamped with work, but if you send a PR I will gladly review and merge.
