### ISSUE TITLE
All key commands don't work

### ISSUE THREAD

**Issue by thomasschiwietz** [googlecartographer/point_cloud_viewer#186]
None of the key commands work anymore.

keymod is always false:
https://github.com/googlecartographer/point_cloud_viewer/blob/master/sdl_viewer/src/lib.rs#L439

related to https://github.com/Rust-SDL2/rust-sdl2/issues/580?

**Comment by SirVer** [comment]
cannot repro on latest master with latest rust stable.

**Comment by DarthBubi** [comment]
This seems to be related to an active num lock or caps lock. In [this](https://github.com/googlecartographer/point_cloud_viewer/blob/master/sdl_viewer/src/lib.rs#L415) statement keymod is only checked for an empty value, which is not the case, if num lock is active. A work around would be to change
 `if keymod.is_empty()` to
`if keymod.is_empty() || keymod.intersects(NUMMOD | CAPSMOD) && !keymod.intersects(LCTRLMOD | RCTRLMOD)`
The last check prevents the following else ifs from breaking. 
Alternatively one could tell the user to disable num lock etc. on the keyboard, which seems inconvenient.

**Comment by codeislife99** [comment]
Please fix this issue. Its very annoying and very non-intuitive.

**Comment by feuerste** [comment]
#287 already fixed the NUMMOD issue. If you think that navigationg with CAPSMOD is required, too, please reopen this issue.
