### ISSUE TITLE
npm install error！

### ISSUE THREAD

**Issue by hel4859** [googlecartographer/point_cloud_viewer#19]
Hi，I am a student and now want to use cartographer to build a 3D map，so i think  the package is so useful for me，but i know less abot java and npm，and when i use npm install ，i face the problem as follows：
npm WARN package.json point_viewer@0.1.0 No repository field.
npm WARN package.json point_viewer@0.1.0 No README data
npm http GET https://registry.npmjs.org/types/three/0.0.27
npm http GET https://registry.npmjs.org/types/dat-gui/0.6.1
npm http GET https://registry.npmjs.org/dat-gui/0.5.0
npm http GET https://registry.npmjs.org/three/0.83.0
npm http GET https://registry.npmjs.org/typescript
npm http 304 https://registry.npmjs.org/typescript
npm http 404 https://registry.npmjs.org/types/three/0.0.27
npm ERR! 404 'types' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 3.16.0-30-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/hl/point_cloud_viewer-master/client
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code E404
npm http 404 https://registry.npmjs.org/types/dat-gui/0.6.1
npm http 304 https://registry.npmjs.org/dat-gui/0.5.0
npm http 304 https://registry.npmjs.org/three/0.83.0
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/hl/point_cloud_viewer-master/client/npm-debug.log
npm ERR! not ok code 0
i have no idea how to solve it，so who can help me？

**Comment by SirVer** [comment]
Your node version is to old. Use nvm to install node.

**Comment by msy22** [comment]
I also have encountered this problem, with the virtually the exact same error message (see below), but installing the latest stable LTS version of Node (I installed v6.11.1) did not solve the problem.

My error message was this:
`root@user:/home/user/repo/workspace/src/point_cloud_viewer/web_viewer/client# npm install
npm WARN package.json point_viewer@0.1.0 No repository field.
npm WARN package.json point_viewer@0.1.0 No README data
npm http GET https://registry.npmjs.org/three/0.83.0
npm http GET https://registry.npmjs.org/dat-gui/0.5.0
npm http GET https://registry.npmjs.org/typescript
npm http GET https://registry.npmjs.org/types/three/0.0.27
npm http GET https://registry.npmjs.org/types/dat-gui/0.6.1
npm http 404 https://registry.npmjs.org/types/dat-gui/0.6.1
npm ERR! 404 'types' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.4.0-31-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/user/repo/workspace/src/point_cloud_viewer/web_viewer/client
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! code E404
npm http 404 https://registry.npmjs.org/types/three/0.0.27
npm http 200 https://registry.npmjs.org/three/0.83.0
npm http 200 https://registry.npmjs.org/dat-gui/0.5.0
npm http GET https://registry.npmjs.org/three/-/three-0.83.0.tgz
npm http GET https://registry.npmjs.org/dat-gui/-/dat-gui-0.5.0.tgz
npm http 200 https://registry.npmjs.org/dat-gui/-/dat-gui-0.5.0.tgz
npm http 200 https://registry.npmjs.org/three/-/three-0.83.0.tgz
npm http 200 https://registry.npmjs.org/typescript
npm http GET https://registry.npmjs.org/typescript/-/typescript-2.4.2.tgz
npm http 200 https://registry.npmjs.org/typescript/-/typescript-2.4.2.tgz
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/user/repo/workspace/src/point_cloud_viewer/web_viewer/client/npm-debug.log
npm ERR! not ok code 0`

In addition, if the latest version of node is necessary for point viewer, should installing/updating it be added to the point viewer installation instructions?
