### ISSUE TITLE
Command not found: build_octree

### ISSUE THREAD

**Issue by Semih67** [googlecartographer/point_cloud_viewer#205]
I have troubles to install the viewer. Everything was fine until I had to run this command: `target/release/build_octree` When I run this I get this output: `error: The following required arguments were not provided:
   <input>
   --output_directory <output_directory

USAGE:
   build_octree <input> --output_directory <output_directory> --resolution <resolution>`

and then I type this but without success: `build_octree /home/nvidia/Documents/bagfiles2/bagfile.bag_points.pcd --output_directory /home/nvidia/Documents/output`

Then I get this: zsh: command  not found: build_octree

While I'm doing this I'm in ~/point_cloud_viewer

EDIT:
And when I try to install the sdl I get also errors with this command: cargo build --release

`error: failed to run custom build command for `grpcio-sys v0.4.0`
process didn't exit successfully: `/home/nvidia/point_cloud_viewer/target/release/build/grpcio-sys-658df6a9d1dd5638/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=grpc_wrap.cc
cargo:rerun-if-changed=grpc
cargo:rerun-if-env-changed=GRPCIO_SYS_USE_PKG_CONFIG
running: "cmake" "/home/nvidia/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.4.0/grpc" "-DgRPC_INSTALL=false" "-DgRPC_BUILD_CSHARP_EXT=false" "-DgRPC_BUILD_CODEGEN=false" "-DCMAKE_INSTALL_PREFIX=/home/nvidia/point_cloud_viewer/target/release/build/grpcio-sys-9a77aecd077dad10/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Release"
-- Configuring incomplete, errors occurred!
See also "/home/nvidia/point_cloud_viewer/target/release/build/grpcio-sys-9a77aecd077dad10/out/build/CMakeFiles/CMakeOutput.log".
See also "/home/nvidia/point_cloud_viewer/target/release/build/grpcio-sys-9a77aecd077dad10/out/build/CMakeFiles/CMakeError.log".

--- stderr
CMake Warning at cmake/protobuf.cmake:48 (message):
  gRPC_PROTOBUF_PROVIDER is "module" but PROTOBUF_ROOT_DIR is wrong
Call Stack (most recent call first):
  CMakeLists.txt:118 (include)

CMake Error at third_party/boringssl/CMakeLists.txt:38 (message):
  Could not find Go

thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', /home/nvidia/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.31/src/lib.rs:643:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed`

But I also could not install the sdl2 with the command cargo install sdl2

**Comment by SirVer** [comment]
seems like you are fighting with your shell... Not something I can really help with.

Also the PCD file is not supported, you'll need a supported PLY file.

You did also not run through the README.md, likely missing a lot of the dependencies (like go and protobuf and sdl2). Best start there?
