### ISSUE TITLE
How to color octree by point coordinate in sdl_viewer?

### ISSUE THREAD

**Issue by Ellon** [googlecartographer/point_cloud_viewer#299]
Hi,

I have a `.ply` file generated from `cartographer_assets_writer`, from which I created an octree with `build_octree` and I managed to visualize it using `sdl_viewer`. My problem is that all points in `sdl_viewer` are white and I would like to colour them based in the point coordinate.

What am I missing? Do I need to add an option to `build_octree` or `sdl_viewer` for that? Or should I update the `.ply` file (adapting `cartographer_assets_writer` pipeline)?

If this is a problem from `cartographer_ros` just tell me and I'll ask there. :)

**Comment by feuerste** [comment]
I'm not familiar with the `cartographer_assets_writer` or `cartographer_ros`, but your `.ply` file needs to include the following in its header:
```
ply
...
property uchar red
property uchar green
property uchar blue
...
end_header
```
Alternatively the color properties can be named `r`, `g`, and `b`.

**Comment by Ellon** [comment]
Hi @feuerste, thanks for your reply. 

I inspected my header and I have no color information:
```
ply
format binary_little_endian 1.0
comment generated by Cartographer
element vertex 000000342933638
property float x
property float y
property float z
property float intensity
end_header
```

So think I should configure `cartographer_assets_writer` to write the colour information. I'll ask there. Thanks again !
